name: Build SolidStart with Bun

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VITE_SESSION_SECRET: ${{ secrets.VITE_SESSION_SECRET }}
      VITE_BACKEND_HOST: ${{ secrets.VITE_BACKEND_HOST }}
      NODE_ENV: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Archive build output
        run: tar -czf build.tar.gz .output

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build.tar.gz
          tag_name: v1.0.${{ github.run_number }}
          body: "📦 SolidStart Bun release"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
