name: Build & Release SolidStart (Bun)

on:
  push:
    tags:
      - 'v*'         # Trigger on version tags like v1.0.0
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Create tarball
        run: tar -czf build.tar.gz .output

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
